### ISSUE TITLE
Some N64 saves contain a different type of data

### ISSUE THREAD

**Issue by euan-forrester** [JanErikGunnar/vcromclaim#3]
e.g. This save https://gamefaqs.gamespot.com/n64/197859-mario-golf/saves contains a file called `RAM_NMFE`, rather than the usual `savedata.bin` which can be parsed like this: https://forums.dolphin-emu.org/archive/index.php?thread-35067-95.html

So presumably vcromclaim would just see the `RAM_NMFE` file?

This was reported by a user on my site

**Comment by euan-forrester** [comment]
Here's my fix, which I tested with that save: https://github.com/euan-forrester/save-file-converter/blob/main/frontend/src/save-formats/Wii/ConvertFromN64.js#L64

**Comment by JanErikGunnar** [comment]
Interesting! Could be related to which type of storage the game has. Maybe SRAM games have RAM_**** files while EEPROM games use savedata.bin.
I think NMFE is game specific, NMFE is the ID for Mario Golf, games can have any 4 character code. Often Wii also identify games by codes like this in hex format (e.g. 4e4d4645)

**Comment by euan-forrester** [comment]
Hah I didn't notice that that was a game ID: good catch! 

It don't think it's related to save type: F-Zero X uses SRAM as well and doesn't need any special handling.

But I think you're right and there was something specific to this game that required something different. I haven't come across any other games like this, and that thread only mentioned Mario Golf, so maybe it's the only one?

That also begs the question about if a Mario Golf save from a different region (it was on Wii VC in PAL regions, and Japan) would have a different filename. I haven't seen a save file from one of them to confirm.

**Comment by JanErikGunnar** [comment]
Fixed! vcromclaim actually handled "RAM_*" files just fine, it just takes whatever it finds of savedata.bin or SRAM_*. (Probably it will break if there are multiple matches).

It broke in Mario Golf though, because of the 48 KiB file size, which is weird because the original cart is only 32 KiB.

I just added support for 48KiB files, at least Project 64 seems to be fine with these files. :)

**Comment by euan-forrester** [comment]
Fair enough! I made it so it truncated the output to the nearest correct size, but both work!
